// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using aoc_2025_p10_2;

#nullable disable

namespace aoc_2025_p10_2.Migrations
{
    [DbContext(typeof(JobDbContext))]
    partial class JobDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("aoc_2025_p10_2.JobResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ActualDurationMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<long>("ButtonPresses")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Found")
                        .HasColumnType("boolean");

                    b.Property<int>("MachineJobId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MachineJobId")
                        .IsUnique();

                    b.ToTable("JobResults");
                });

            modelBuilder.Entity("aoc_2025_p10_2.MachineJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonsData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EstimatedDurationSeconds")
                        .HasColumnType("bigint");

                    b.Property<int>("MachineNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkerId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EstimatedDurationSeconds");

                    b.HasIndex("Status");

                    b.ToTable("MachineJobs");
                });

            modelBuilder.Entity("aoc_2025_p10_2.JobResult", b =>
                {
                    b.HasOne("aoc_2025_p10_2.MachineJob", "MachineJob")
                        .WithOne("Result")
                        .HasForeignKey("aoc_2025_p10_2.JobResult", "MachineJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineJob");
                });

            modelBuilder.Entity("aoc_2025_p10_2.MachineJob", b =>
                {
                    b.Navigation("Result");
                });
#pragma warning restore 612, 618
        }
    }
}
